# name of the conda environment
name: fidimag_docs

# add channel for pandoc
channels:
  - ccordoba12

dependencies:
  - pandoc
  - nbformat
  - pip:
      - nbsphinx
      - git+https://github.com/pandas-dev/pydata-sphinx-theme.git@master
