#pragma once
#include <cstddef>
#define FMMGEN_MINORDER 2
#define FMMGEN_MAXORDER 13
#define FMMGEN_SOURCEORDER 1
#define FMMGEN_SOURCESIZE 3
#define FMMGEN_OUTPUTSIZE 3
#define FMMGEN_COMPRESSED 1
/* Array sizes for the *c-suffixed* operators only. The trace-free
   basis drops the C(p+3,3) - (p+1)^2 redundant coefficients, so these
   are (p+1)^2; the unsuffixed operators still take Nterms(order).
   Index by order. */
static const size_t FMMGEN_MULTIPOLESIZE[] = {0, 3, 8, 15, 24, 35, 48, 63, 80, 99, 120, 143, 168, 195};
static const size_t FMMGEN_LOCALSIZE[] = {0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169};
#define FMMGEN_PLANAR 1
/* Array sizes for the *xy-suffixed* operators only. Retained set is
   n_z <= source_order for the multipole array, n_z <= 1 (field) or
   <= 0 (potential only) for the local array. Index by order. */
static const size_t FMMGEN_PLANAR_MULTIPOLESIZE[] = {0, 3, 8, 15, 24, 35, 48, 63, 80, 99, 120, 143, 168, 195};
static const size_t FMMGEN_PLANAR_LOCALSIZE[] = {0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169};
void S2M_2(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_2(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_2(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_2(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_2(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_2(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_2(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_2(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_2(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_2(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_2(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_2(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_2(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_2(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_2(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_2(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_2(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_2(double x, double y, double z, double * __restrict M, double * __restrict L);
void P2P(double x, double y, double z, double * __restrict S, double * __restrict F);
void P2P_batch(double tx, double ty, double tz, const double * __restrict sx, const double * __restrict sy, const double * __restrict sz, const double * __restrict S, size_t begin, size_t end, double * __restrict F);
void P2Pxy(double x, double y, double * __restrict S, double * __restrict F);
void P2P_batchxy(double tx, double ty, const double * __restrict sx, const double * __restrict sy, const double * __restrict S, size_t begin, size_t end, double * __restrict F);
void S2M_3(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_3(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_3(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_3(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_3(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_3(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_3(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_3(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_3(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_3(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_3(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_3(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_3(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_3(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_3(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_3(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_3(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_3(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_4(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_4(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_4(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_4(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_4(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_4(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_4(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_4(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_4(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_4(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_4(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_4(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_4(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_4(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_4(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_4(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_4(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_4(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_5(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_5(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_5(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_5(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_5(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_5(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_5(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_5(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_5(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_5(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_5(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_5(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_5(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_5(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_5(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_5(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_5(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_5(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_6(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_6(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_6(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_6(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_6(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_6(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_6(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_6(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_6(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_6(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_6(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_6(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_6(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_6(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_6(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_6(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_6(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_6(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_7(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_7(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_7(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_7(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_7(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_7(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_7(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_7(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_7(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_7(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_7(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_7(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_7(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_7(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_7(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_7(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_7(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_7(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_8(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_8(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_8(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_8(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_8(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_8(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_8(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_8(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_8(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_8(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_8(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_8(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_8(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_8(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_8(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_8(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_8(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_8(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_9(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_9(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_9(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_9(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_9(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_9(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_9(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_9(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_9(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_9(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_9(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_9(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_9(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_9(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_9(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_9(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_9(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_9(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_10(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_10(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_10(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_10(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_10(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_10(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_10(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_10(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_10(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_10(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_10(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_10(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_10(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_10(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_10(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_10(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_10(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_10(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_11(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_11(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_11(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_11(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_11(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_11(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_11(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_11(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_11(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_11(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_11(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_11(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_11(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_11(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_11(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_11(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_11(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_11(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M_12(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2M_12(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void M2L_12(double x, double y, double z, double * __restrict M, double * __restrict L);
void L2L_12(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2P_12(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2P_12(double x, double y, double z, double * __restrict M, double * __restrict F);
void S2Mc_12(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mc_12(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lc_12(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pc_12(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pc_12(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lc_12(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2Mxy_12(double x, double y, double z, double * __restrict S, double * __restrict M);
void M2Mxy_12(double x, double y, double z, double * __restrict M, double * __restrict Ms);
void L2Lxy_12(double x, double y, double z, double * __restrict L, double * __restrict Ls);
void L2Pxy_12(double x, double y, double z, double * __restrict L, double * __restrict F);
void M2Pxy_12(double x, double y, double z, double * __restrict M, double * __restrict F);
void M2Lxy_12(double x, double y, double z, double * __restrict M, double * __restrict L);
void S2M(double x, double y, double z, double * __restrict S, double * __restrict M, int order);
void M2M(double x, double y, double z, double * __restrict M, double * __restrict Ms, int order);
void M2L(double x, double y, double z, double * __restrict M, double * __restrict L, int order);
void L2L(double x, double y, double z, double * __restrict L, double * __restrict Ls, int order);
void L2P(double x, double y, double z, double * __restrict L, double * __restrict F, int order);
void M2P(double x, double y, double z, double * __restrict M, double * __restrict F, int order);
void S2Mc(double x, double y, double z, double * __restrict S, double * __restrict M, int order);
void M2Mc(double x, double y, double z, double * __restrict M, double * __restrict Ms, int order);
void L2Lc(double x, double y, double z, double * __restrict L, double * __restrict Ls, int order);
void L2Pc(double x, double y, double z, double * __restrict L, double * __restrict F, int order);
void M2Pc(double x, double y, double z, double * __restrict M, double * __restrict F, int order);
void M2Lc(double x, double y, double z, double * __restrict M, double * __restrict L, int order);
void S2Mxy(double x, double y, double z, double * __restrict S, double * __restrict M, int order);
void M2Mxy(double x, double y, double z, double * __restrict M, double * __restrict Ms, int order);
void L2Lxy(double x, double y, double z, double * __restrict L, double * __restrict Ls, int order);
void L2Pxy(double x, double y, double z, double * __restrict L, double * __restrict F, int order);
void M2Pxy(double x, double y, double z, double * __restrict M, double * __restrict F, int order);
void M2Lxy(double x, double y, double z, double * __restrict M, double * __restrict L, int order);
